name: Check on PRs and push

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          cache: true
          go-version-file: "go.mod"
          cache-dependency-path: "go.sum"

      - name: Run GolangCI-Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.49

  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          cache: true
          go-version-file: "go.mod"
          cache-dependency-path: "go.sum"

      - name: Run Unit tests
        run: |
          go test -v -race -coverpkg=./... -coverprofile=coverage.out -covermode=atomic ./...
      - name: Clean test coverage
        run: cat ./coverage.out | grep -v -e "_easyjson.go" -e "cmd" -e "entities" > cover.out

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./cover.out
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true